#!/bin/bash

cat <<EOT
=====================================================================
SYNDESIS QUICKSTART

Hybrid integration on OpenShift made easy
=====================================================================

EOT

read -p "This install will reset your current MiniShift. OK to continue? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then

  curl -LO https://github.com/syndesisio/syndesis/archive/master.zip
  unzip ./master.zip 'syndesis-master/tools/bin/*'
  if [ -d ".syndesis" ]; then
    rm -fr .syndesis
  fi
  mkdir .syndesis
  mv syndesis-master/tools/bin ./.syndesis
  rm -fr syndesis-master
  rm master.zip

  ./.syndesis/bin/syndesis minishift --install --full-reset --open

fi
