#!/bin/bash

cat <<EOT
=====================================================================
SYNDESIS QUICKSTART

Hybrid integration on OpenShift made easy
=====================================================================

Prerequisites: Minishift https://www.okd.io/minishift/
Quickstarts: https://github.com/syndesisio/syndesis-quickstarts/blob/master/README.md#4-lets-run-some-quickstarts

EOT

read -p "This install will reset your current MiniShift. OK to continue [y/N]? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then

  tempDir=$(mktemp -d)
  pushd $tempDir
  curl -LO https://github.com/syndesisio/syndesis/archive/master.zip
  unzip ./master.zip 'syndesis-master/tools/bin/*'
  mkdir .syndesis
  mv syndesis-master/tools/bin ./.syndesis
  rm -fr syndesis-master
  rm master.zip

  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Hyperkit support only on OSX"
    ./.syndesis/bin/syndesis minishift --install --full-reset --nodev --open --vm-driver hyperkit
  else
    ./.syndesis/bin/syndesis minishift --install --full-reset --nodev --open
  fi
  popd

fi
